<?php
  unset($location);
  unset($product_name);
  unset($ral_no);
  unset($color_name);
  unset($size);
  unset($spc);
  unset($rgb_code);
  unset($last_stock);
  
  unset($slsProduct_name);
  unset($slsRal_no);
  unset($slsColor_name);
  unset($slsSize);
  unset($slsSpc);
  unset($slsRgb_code);
  unset($slsLast_stock);
  unset($slsLocation);
 ?>
